version: '3.9'

services:

  fs:
    container_name: tfg-fs
    hostname: fs
    build:
      context: ./file-stograge-service
    ports:
      - 9000:80
    volumes:
      - ./.docker/fs:/home/fs


networks:
  tfg-network:
    driver: bridge